services:
  proxy:
    image: ghcr.io/retch/docker-tor-privoxy-alpine:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8118"
      - "127.0.0.1:9000:9050"
    healthcheck:
      test: https_proxy="127.0.0.1:8118" wget --no-verbose --tries=1 --spider https://cloudflare.com || exit 1
      interval: 2m
      timeout: 10s
      retries: 1
      start_period: 1m
