name: 'build docker-tor-privoxy-alpine'

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Owner/Repository to lower
        id: ownerrepo
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm
